;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="GameplayCue.BurstImpact",DevComment="GameplayCue for Burst Impact")
+GameplayTagList=(Tag="GameplayCue.HitReact",DevComment="Tag for the Hit React GameplayCue")
+GameplayTagList=(Tag="GCTags.Abilities.BlockHitReact",DevComment="Tag for Blocking Hit React")
+GameplayTagList=(Tag="GCTags.Abilities.Death",DevComment="")
+GameplayTagList=(Tag="GCTags.Cooldown.Secondary",DevComment="")
+GameplayTagList=(Tag="GCTags.Events.Player.Primary",DevComment="Tag for the Primary Gameplay Ability")
+GameplayTagList=(Tag="GCTags.Events.Player.Secondary",DevComment="Event Tag for Secondary Ability")
+GameplayTagList=(Tag="GCTags.GC.Abilities.Enemy.HitReact",DevComment="Tag for the Enemy Hit React Ability")
+GameplayTagList=(Tag="GCTags.SetByCallers.Melee",DevComment="Set by caller Data Tag for Melee Attacks")
+GameplayTagList=(Tag="GCTags.SetByCallers.Player.Secondary",DevComment="")
+GameplayTagList=(Tag="GCTags.Status.Dead",DevComment="")

