;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="GCTags.Abilities.Death",DevComment="")
+GameplayTagList=(Tag="GCTags.Events.Player.Primary",DevComment="Tag for the Primary Gameplay Ability")
+GameplayTagList=(Tag="GCTags.GC.Abilities.Enemy.HitReact",DevComment="Tag for the Enemy Hit React Ability")
+GameplayTagList=(Tag="GCTags.Status.Dead",DevComment="")

